### ISSUE TITLE
twenty million records insert meet computer down

### ISSUE THREAD

**Issue by VivianSnow** [balena/radixdb#1]
Hi, I want to make a radixdb from a file which contains twenty million passwords length from 6Byte to 101Byte with total size 1.02GB, and I write my program follow the code in tests folds, but unfortunately I meet a computer crash down on my laptop with Ubuntu OS and 4GB memory.After that I test the data in tests and one tens of my 1.02GB data, in this case program runs well.So, can you help me with this problem?

**Comment by balena** [comment]
Hello. I can't tell you exactly why you get a crash without evaluating your source code, but I don't think you had a memory overflow because you would have plenty of virtual memory to couple with the extra overhead of the radixdbmk program (or a derivative on your own program). I can tell you is that the `radixdb_make` functions don't use compact structures of memory, so the overhead may be significant (say that you can get more than 530MB for your 20m passwords).

Is it possible for you to copy at least some meaningful parts of the function that make use of the `radixdb_make` functions?

**Comment by balena** [comment]
I'm going to close this issue due to inactivity.
